CREATE TABLE IF NOT EXISTS `TB_USER`
(
    `US_ID` INT AUTO_INCREMENT,
    `US_USER_NAME` VARCHAR(25) NOT NULL,
    `US_PASSWORD` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`US_ID`)
);

CREATE TABLE IF NOT EXISTS `TB_ARTICLE`
(
    `AR_ID` INT AUTO_INCREMENT,
    `AR_CONTENT` VARCHAR(1000) NOT NULL,
    `AR_USER_ID` INT NOT NULL,
    PRIMARY KEY (`AR_ID`),
    FOREIGN KEY fk_user_id (AR_USER_ID)
        REFERENCES TB_USER (US_ID)
);